spring:
    datasource:
        url: jdbc:mysql://localhost:3306/nexchange?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: blueman2002
        driver-class-name: com.mysql.cj.jdbc.Driver

