spring:
    datasource:
        url: jdbc:mysql://localhost:3306/nexchange?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: blueman2002
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
        host: smtp.163.com
        username: skillup163@163.com    #发送方邮箱
        password: FVXGAWGELNKQDWVK    #发送方邮箱授权码
        protocol: smtp    #发送邮件协议
        properties:
            mail:
                smtp:
                    ssl:
                        enable: true #开启SSL
        default-encoding: utf-8

    #springdoc相关配置
    springdoc:
        swagger-ui:
            #自定义swagger前端请求路径，输入http：127.0.0.1:8080/swagger-ui.html会自动重定向到swagger页面
            path: /swagger-ui.html
            tags-sorter: alpha
            operations-sorter: alpha
        api-docs:
            path: /v3/api-docs    #swagger后端请求地址
            enabled: true   #是否开启文档功能
        group-configs:
            - group: 'org.nexchange.controller'
              paths-to-match: '/**'
              packages-to-scan: org.nexchange.controller    #按包路径匹配:一般到启动类的包名

    #knife4j相关配置 可以不用改
    knife4j:
        enable: true    #开启knife4j，无需添加@EnableKnife4j注解
        setting:
            language: zh_cn   #中文
            swagger-model-name: 实体类   #重命名SwaggerModel名称,默认
        #开启Swagger的Basic认证功能,默认是false
        basic:
            enable: true
            # Basic认证用户名
            username: ljj
            # Basic认证密码
            password: 123456

    #Security
#    security:
#        jwt:
#            key: qwertyuiop
#            expire: 7




